<!DOCTYPE html>
<html>
<head>
<title>TP PHP MVC</title>
	<link rel="stylesheet" type="text/css" href="<?php echo dirname('/');?>css/styles.css">
    <link rel="stylesheet" type="text/css" href="<?php echo dirname('/');?>css/styleRest.css">
    <script type="text/javascript" src="<?php echo dirname('/');?>js/jquery-3.2.0.min.js"></script>
    <script type="text/javascript" src="<?php echo dirname('/');?>js/RestClient.js"></script>

</head>

<body>

<header>
<?php if(!isset($_SESSION['user'])):?>
<nav>
	<ul>
		<li><a href="<?php echo dirname('/');?>index.phtml">Accueil</a></li>
		<li><a href="<?php echo dirname('/');?>register.phtml">S'inscrire</a></li>
		<li><a href="<?php echo dirname('/');?>login.phtml">Se connecter</a></li>

	</ul>
</nav>
<?php else: ?>
<nav>
	<ul>
		<li><a href="<?php echo dirname('/');?>index.phtml">Accueil</a></li>
        <li><a href="<?php echo dirname('/');?>Article/list_articles">Listes des Articles</a></li>
        <li><a href="<?php echo dirname('/');?>Article/manage_articles">Manage Articles</a></li>
        <li><a href="<?php echo dirname('/');?>Utilisateur/profile">Profile (<?php echo $_SESSION['user']['nom'];?>)</a></li>
		<li><a href="<?php echo dirname('/');?>Utilisateur/logout">Se déconnecter</a></li>

	</ul>
</nav>
<?php endif; ?>
</header>